### ISSUE TITLE
ZopeTransactionExtension is gone.

### ISSUE THREAD

**Issue by ztane** [sacrud/ps_alchemy#11]
Use ZopeTransactionEvents.

Also, are you still using sacrud/pyramid_sacrud; if the project is up for adoption, we're interested in assuming maintainership...

**Comment by ztane** [comment]
https://github.com/sacrud/ps_alchemy/pull/12

**Comment by uralbash** [comment]
@ztane  I am not developing this project yet. If you're interested, I can add you to maintainer
